config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'user/personal/:id' => 'users#personal',as:"user_personal"
  get 'user/favorite/:id' => 'users#favorite',as:"user_favorite"
  get 'search' => 'searchs#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :nices, only: [:create, :destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :post
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/picture.rb
class Picture < ApplicationRecord

  belongs_to :post
  attachment :picture
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :category
  belongs_to :member
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :nices, dependent: :destroy

  accepts_attachments_for :pictures, attachment: :picture

  def niced_by?(user)
    nices.where(user_id: user.id).exists?
  end

  def Post.search(search, user_or_post)
    if user_or_post == "2"
      if search == ""
        Post.where(['title LIKE ?',"#{search}" ])
      else
        Post.where(['title LIKE ?', "%#{search}%"])
      end
    end
  end

  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { maximum: 10 }
  validates :name, length: { minimum: 2 }
  validates :name, presence: true
  validates :introduction, length: { maximum: 30 }
  attachment :profile_image

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  #「follower」モデルのUserを集め「followings」と定義。
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  #「following」モデルのUserを集め「followers」と定義。
  has_many :followers, through: :passive_relationships, source: :following

  accepts_attachments_for :pictures, attachment: :picture



  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def User.search(search, user_or_post)
    if user_or_post == "1"
      if search == ""
        User.where(['name LIKE ?', "#{search}"])
      else
        User.where(['name LIKE ?', "%#{search}%"])
      end
    end
  end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.new(comment_params)
    comment.user_id = current_user.id
    comment.star = params[:review][:star]
    comment.save
    redirect_to request.referer
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to request.referer
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/nices_controller.rb
class NicesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    nice = post.nices.new(user_id: current_user.id)
    nice.save
    redirect_to request.referer
  end

  def destroy
    post = Post.find(params[:post_id])
    nice = post.nices.find_by(user_id: current_user.id)
    nice.destroy
    redirect_to request.referer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.pictures.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      @post.pictures.new
      render "new"
    end
  end

  def index
    @posts=Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @category = @post.category
    @pictures = @post.pictures
    @comment=Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    if current_user != @post.user
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id),notice: "投稿の更新に成功しました"
    else render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path,notice: "投稿を削除しました"
  end

  private
  def post_params
    params.require(:post).permit(:title, :caption, :member_id, :category_id, pictures_pictures: [])
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def search
    @user_or_post = params[:option]
    @how_search = params[:choice]
    @search = params[:search]
    if @user_or_post == "1"
      @users = User.search(params[:search], @user_or_post)
    elsif @user_or_post == "2"
      @posts = Post.search(params[:search], @user_or_post)
    else
      @user=User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path
    end
  end

  def personal
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_personal_path(@user.id),notice: "パーソナル情報の更新に成功しました"
    else
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/nices_helper.rb
module NicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_alert.html.erb
<div class="alert alert-danger">
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/posts/_comment.html.erb
<div class="center-block">
      <div class="adjustment">
        <div class="panel panel-warning">
          <div class="panel-heading comment-index">
            コメント一覧
          </div>
          <!-- コメント投稿がある場合のみ下記を表記 -->
          <% unless @post.comments.empty? %>
            <div class="panel-body">
              <table class="table table-hover comment-table">
                <% @post.comments.each do |comment| %>
                  <tr>
                    <td>
                      <%=link_to user_personal_path(comment.user.id) do %>
                      <%=attachment_image_tag comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "default.jpg" %>
                      <%= comment.user.name %>
                      <% end %>
                    </td>
                    <td>
                      <%= comment.comment %>
                    </td>
                    <td>
                      <i class="fas fa-star star-icon z"></i><%= comment.star %>
                    </td>
                    <td>
                      <!-- ログイン時 -->
                      <% if user_signed_in? %>
                        <!-- current_userのみ表記 -->
                        <% if @user == current_user %>
                          <%=link_to "", post_comment_path(comment.post, comment),method: :delete,"data-confirm"=>"本当に削除しますか?", class:"fas fa-trash-alt y" %>
                        <% end %>
                      <% end %>
                      <!-- ここまで -->
                    </td>
                  </tr>
                <% end %>
              </table>
            </div>
          <% end %>
          <!-- ここまで -->
        </div>
      </div>
      <!-- ログイン時 -->
      <% if user_signed_in? %>
        <div class="forms">◎投稿フォーム</div>
        <%=form_for [@post, @comment] do |f| %>
          <%=f.text_area :comment, class:"btn-block" %>
          <p class="form">
            <%= f.label :画像 %>
          </p>
          <%= f.label :評価 %>
          <span class="star"></span>
          <%= f.hidden_field :star, id: :review_star %>
          <div class="adjustment">
            <%=f.submit "投稿",class: "btn btn-primary" %>
          </div>
        <% end %>
      <% end %>
      <!-- ここまで -->
</div>

<script>
  $('.star').raty({
    size: 36, // 星のサイズ
    score: "<%= @comment.star %>",//数値の代入
    starOff: "<%=asset_path('star-off.png')%>",// 星なし
    starOn: "<%=asset_path('star-on.png')%>",//星有り
    starHalf: "<%=asset_path('star-half.png')%>",// 星半分
    scoreName: 'review[star]',
    half: true,// 星の半分の入力を実行
  });
</script>

app/views/posts/_form.html.erb
<%= form_with model:@post, html:{name: 'form'} do |f| %>
  <p class="form">
    <%= f.label :推しメン選択 %>
    <%= f.collection_select :member_id, Member.all, :id, :member,class:"select-controll" %>
  </p>
  <p class="form">
    <%= f.label :タイトル %>
    <%= f.text_field :title,class:"btn-block form-controll" %>
  </p>
  <p class="form">
    <%= f.label :本文 %>
    <%= f.text_area :caption,class:"btn-block form-controll" %>
    <!-- idを加えることでgetElementById("select_file")をとれる。 -->
  </p>
  <p class="form">
    <%= f.label :添付画像選択（複数投稿可） %>
    <%= f.attachment_field :pictures_pictures, multiple: true, id:"select_image" %>
  </p>
  <p class="form">
    <%= f.label :カテゴリー %>
    <%= f.collection_select :category_id, Category.all, :id, :genre,class:"select-controll" %>
  </p>
  <div class="submit-button">
    <%= f.submit "投稿する",class: "btn btn-primary btn-block post-button",id:"submit_button" %>
  </div>
<% end %>

app/views/posts/_script.html.erb
<script>
  submit_button.addEventListener('click',(e) => {
    e.preventDefault();
    // preventDefault()=クリックイベントを無効化。無効化しないと無条件にデータを送信してします。
    var files = document.getElementById("select_image").files;
    // <div><h1>は全てElement。なので、select_fileという名前がついたid(Element)を呼び出す
    // files=html上の選択ボックスのtype
    if(files.length > 2) {
      alert('画像ファイルは2枚以内で投稿して下さい');
    }
    else {
       document.form.submit();
       // このformは5行目で任意につけたフォーム。このdocument.form.submit()で、preventDefault();で無効化したものを再度有効化している。
    }
  });
</script>

app/views/posts/edit.html.erb
<div class="post-form">
  <div class="container">
    <div class="row">
      <div class="col-xs-1"></div>
      <div class=" col-xs-10">
        <h3 class="new_post">投稿編集</h3>
          <% if @post.errors.any? %>
            <%= render 'posts/alert', post: @post %>
          <% end %>
         <%= render 'posts/form', post: @post %>
     </div>
     <div class="col-xs-1"></div>
   </div>
 </div>
</div>
<%= render 'posts/script', post: @post %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
      <table class="table table-hover table-invrese">
        <thead>
          <tr>
            <th>投稿者</th>
            <th>タイトル</th>
            <th>推しメン</th>
            <th>カテゴリー</th>
            <th><i class="fas fa-heart"></th>
            <th><i class="far fa-clock"></i></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
              <tr>
                <td>
                  <%=link_to user_personal_path(post.user.id) do %>
                    <%= attachment_image_tag post.user, :profile_image, size: "50x50",format: 'jpeg', fallback: "default.jpg" %><br>
                    <%= post.user.name %>
                  <% end %>
                </td>
                <td>
                  <%=link_to post.title, post_path(post.id) %>
                </td>
                <td>
                  <%= post.member.member %>
                </td>
                <td>
                  <%= post.category.genre %>
                </td>
                <td>
                  <%= post.nices.count %>
                </td>
                <td>
                  <%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/posts/new.html.erb
<div class="post-form">
  <div class="container">
    <div class="row">
      <div class="col-xs-1"></div>
      <div class=" col-xs-10">
        <h3 class="new_post">新規投稿</h3>
          <% if @post.errors.any? %>
            <%= render 'posts/alert', post: @post %>
          <% end %>
         <%= render 'posts/form', post: @post %>
     </div>
     <div class="col-xs-1"></div>
   </div>
 </div>
</div>
<%= render 'posts/script', post: @post %>

app/views/posts/show.html.erb
<div class="container">
  <h1 class="detail-title">ここがイチオシ！！</h1>
    <div class="row center-block">
      <span class="label label-primary">投稿者:<%= @user.name %></span>
      <span class="label label-primary">投稿日時:<%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span><br>
      <span class="label label-primary">推しメン:<%= @post.member.member %></span>
      <span class="label label-primary">カテゴリー:<%= @post.category.genre %></span>
      <div class="post-show-buttons">
      <!-- ログイン時 -->
        <% if user_signed_in? %>
          <% if @user == current_user %>
            <span class="edit-button">
              <%= link_to "編集", edit_post_path(@post.id), class:"btn btn-success btn-sm" %>
            </span>
            <span class="destroy-button">
              <%= link_to "削除", post_path(@post.id),"data-confirm"=>"本当に削除しますか?", class:"btn btn-danger btn-sm", method: :delete %>
            </span>
          <% end %>
        <% end %>
        <div class=heart>
          <% if user_signed_in? %>
            <% if @post.niced_by?(current_user) %>
              <%= link_to post_nices_path(@post.id), method: :delete, remote: :true do %>
                <i class="fas fa-heart favorite"></i>
                <%= @post.nices.count %>件
              <% end %>
            <% else %>
              <%= link_to post_nices_path(@post.id), method: :post, remote: :true do %>
                 <i class="far fa-heart favorite"></i>
                 <%= @post.nices.count %>件
              <% end %>
            <% end %>
          <% end %>
      </div>
        <!-- ここまで -->
      </div>
    </div>
    <div class="row center-block">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <p class="average stars"></p><%= @post.title %>
        </div>
        <div class="panel-body">
          <%= @post.caption %>
        </div>
      </div>
    </div>
    <div class="row text-center">
      <% @pictures.each do |picture| %>
        <%= attachment_image_tag picture, :picture, format: 'jpeg', size:'310x310' %>
      <% end %>
    </div>
    <div class="row comment-space">
    <%= render 'posts/comment', post: @post %>
  </div>
  <div class="text-center">
    <%= link_to"投稿一覧に戻る", posts_path,class: "btn btn-primary" %>
  </div>
</div>

<script>
  $('.average').raty({
    size: 36, // 星のサイズ
    score: "<%=@post.comments.average(:star).to_f.round(1) %>",//星の平均値。小数点第１。
    starOff: "<%=asset_path('star-off.png')%>",// 星なし
    starOn: "<%=asset_path('star-on.png')%>",//星有り
    starHalf: "<%=asset_path('star-half.png')%>",// 星半分
    scoreName: 'review[star]',
    half: true,// 星の半分の入力を実行
    readOnly: true, //星の評価を固定化
  });
</script>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-1"></div>
      <div class=" col-xs-10">
        <h3 class="profile-edit">プロフィール編集</h3>
        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <% if @user.errors.any? %>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <% end %>
        <%= form_with(model: @user, local: true) do |f| %>
          <p class="form">
            <%= f.label :ユーザー名 %>
            <%= f.text_field :name,class:"btn-block" %>
          </p>
          <p class="form">
            <%= f.label :自己紹介（30字以内）  %>
            <%= f.text_area :introduction,class:"btn-block" %>
          </p>
          <p class="form">
            <%= f.label :プロフィール画像 %>
            <%=f.attachment_field :profile_image %>
          </p>
          <p class="update_btn">
            <%= f.submit "更新",class:"btn btn-block btn-primary" %>
          </p>
        <% end %>
      </div>
      <div class="col-xs-1"></div>
    </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <h3>Followers Users</h3>

      <% if @users.present? %>
       <table class="table table-hover table-invrese">
         <thead>
           <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
           </tr>
         </thead>
         <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%=attachment_image_tag user, :profile_image, size: "40x40",
              format: 'jpeg', class: "img-circle", fallback: "default.jpg" %>
            </td>
            <td>
              <%=user.name %>
            </td>

            <td>
              フォロー数:<%= user.followings.count %>
            </td>

            <td>
              フォロワー数:<%= user.followers.count %>
            </td>

            <td>
              <%=link_to "投稿一覧画面へ" ,user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
    <div class="col-xs-1"></div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
      <h3>Follows Users</h3>

      <% if @users.present? %>
       <table class="table table-hover table-invrese">
         <thead>
           <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
           </tr>
         </thead>
         <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%=attachment_image_tag user, :profile_image, size: "40x40",
              format: 'jpeg', class: "img-circle", fallback: "default.jpg" %>
            </td>
            <td>
              <%=user.name %>
            </td>

            <td>
              フォロー数:<%= user.followings.count %>
            </td>

            <td>
              フォロワー数:<%= user.followers.count %>
            </td>

            <td>
              <%=link_to "Show" ,user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
    <div class="col-xs-1"></div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
      <div class="text-center">
        <h3><i class="fas fa-user-circle icon"></i></h3>
      </div>
    </div>
    <div class="row">
      <table class="table table-hover table-invrese">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>自己紹介</th>
            <th></th>
            <!-- <th></th> -->
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
              <tr>
                <td>
                  <%=link_to user_personal_path(user.id) do %>
                    <%= attachment_image_tag user, :profile_image, size: "50x50",
                      format: 'jpeg', fallback: "default.jpg" %><br>
                    <%= user.name %>
                  <% end %>
                </td>
                <td>
                  <%= user.introduction %>
                </td>
                <td>
                  <%=link_to "投稿一覧画面" ,user_path(user.id),method: :get %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/users/personal.html.erb
<div class="container">
  <div class="row text-center">
    <% if @user == current_user %>
      <h1>マイページ</h1>
    <% else %>
      <h1><%= @user.name %>さんのプロフィール</h1>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <%= attachment_image_tag @user, :profile_image, size:"210x210", format: "jpeg", class: "img-circle", fallback: "default.jpg" %><br>

      <div class="table">
        <tbody>
          <tr class="profile">
            <th>follows</th>
            <%# if current_user != @user %>
              <th><%=link_to follows_user_path(current_user) do %>
                  <%= current_user.followings.count  %>
                <% end %>
              </th>
            <%# end %>
          </tr>
          <tr>
            <th>followers</th>
            <%# if current_user != @user %>
              <th><%=link_to followers_user_path(current_user) do %>
                    <%= current_user.followers.count %>
                  <% end %>
              </th>
            <%# end %>
          </tr>
        </tbody>
      </div>


      <% if @user != current_user %>
        <% if @user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
        <% end %>
      <% end %>

      <% if @user == current_user %>
        <%= link_to "プロフィール修正", edit_user_path(@user.id) %>
      <% end %>
    </div>
    <div class="col-xs-8">
      <div class="panel panel-info">
        <div class="panel-heading introduction-space">自己紹介</div>
        <div class="panel-body">
          <%= @user.introduction %>
        </div>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <% if @user == current_user %>
      <%= link_to "推しメン投稿する",new_post_path %><br>
    <% end %>
    <%= link_to "投稿一覧",user_path(@user.id) %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
      <h3 class="text-center">
        <% if current_user = @user %>
          My投稿一覧
        <% else %>
          <%= @user.name %>様の投稿一覧
        <% end %>
      </h3>
    </div>

    <div class="row">
      <table class="table table-hover table-invrese">
        <thead>
          <tr>
            <th>推しメン</th>
            <th>タイトル</th>
            <th>投稿日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= post.member.member %>
              </td>
              <td>
                <%= post.title %>
              </td>
              <td>
                <%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>
              <td>
                <%= link_to "詳細画面" ,post_path(post.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>