config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'user/personal/:id' => 'users#personal',as:"user_personal"
  get 'user/favorite/:id' => 'users#favorite',as:"user_favorite"
  get 'search' => 'searchs#search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :nices, only: [:create, :destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :post
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/picture.rb
class Picture < ApplicationRecord

  belongs_to :post
  attachment :picture
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :category
  belongs_to :member
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :nices, dependent: :destroy

  accepts_attachments_for :pictures, attachment: :picture

  def niced_by?(user)
    nices.where(user_id: user.id).exists?
  end

  def Post.search(search, user_or_post)
    if user_or_post == "2"
      if search == ""
        Post.where(['title LIKE ?',"#{search}" ])
      else
        Post.where(['title LIKE ?', "%#{search}%"])
      end
    end
  end

  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { maximum: 10 }
  validates :name, length: { minimum: 2 }
  validates :name, presence: true
  validates :introduction, length: { maximum: 30 }
  attachment :profile_image

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  #「follower」モデルのUserを集め「followings」と定義。
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  #「following」モデルのUserを集め「followers」と定義。
  has_many :followers, through: :passive_relationships, source: :following

  accepts_attachments_for :pictures, attachment: :picture



  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def User.search(search, user_or_post)
    if user_or_post == "1"
      if search == ""
        User.where(['name LIKE ?', "#{search}"])
      else
        User.where(['name LIKE ?', "%#{search}%"])
      end
    end
  end

  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/nices_controller.rb
class NicesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    nice = post.nices.new(user_id: current_user.id)
    nice.save
    redirect_to request.referer
  end

  def destroy
    post = Post.find(params[:post_id])
    nice = post.nices.find_by(user_id: current_user.id)
    nice.destroy
    redirect_to request.referer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.pictures.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      @post.pictures.new
      render "new"
    end
  end

  def index
    @posts=Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @category = @post.category
    @pictures = @post.pictures
    @comment=Comment.new
  end

  def edit
    @post = Post.find(params[:id])
    if current_user != @post.user
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id),notice: "投稿の更新に成功しました"
    else render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path,notice: "投稿を削除しました"
  end

  private
  def post_params
    params.require(:post).permit(:title, :caption, :member_id, :category_id, pictures_pictures: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path
    end
  end

  def personal
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_personal_path(@user.id),notice: "パーソナル情報の更新に成功しました"
    else
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/nices_helper.rb
module NicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top header-color">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <span id="application-name">乃木坂46応援サイト</span>
      </div>
    </div>
    <nav id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- data-toggle="modal"　data-target="#sampleModal" モーダルを開くコード -->
        <!--ログイン時 -->
        <% if user_signed_in? %>
          <li class="menu">
            <%= link_to ' Personal',user_personal_path(current_user),class:"glyphicon glyphicon-home" %>
          </li>
          <li class="menu">
            <%= link_to ' User',users_path, class:"glyphicon glyphicon-user" %>
          </li>
          <li class="menu">
            <%= link_to ' Post',posts_path ,class:"glyphicon glyphicon-list-alt" %>
          </li>
          <li class="menu">
            <a href="" data-toggle="modal" data-target="#sampleModal">
              <i class="fas fa-search"></i>
            </a>
          </li>
          <li class="menu">
             <%= link_to ' Logout', destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out logout"%>
          </li>
            <!--ログアウト時 -->
        <% else %>
          <li class="menu">
            <%= link_to ' Home',root_path,class:"glyphicon glyphicon-home" %>
          </li>
          <li class="menu">
            <%= link_to ' About',home_about_path,class:"glyphicon glyphicon-link" %>
          </li>
          <!-- <li class="menu"> -->
            <%#= link_to ' User',users_path, class:"glyphicon glyphicon-user" %>
          <!-- </li> -->
          <!-- <li class="menu"> -->
            <%#= link_to ' Post',posts_path ,class:"glyphicon glyphicon-list-alt" %>
          <!-- </li> -->
          <li class="menu">
            <%= link_to ' Signup', new_user_registration_path,class:"glyphicon glyphicon-edit" %>
          </li>
          <li class="menu">
            <%= link_to ' Login', new_user_session_path ,class:"glyphicon glyphicon-log-in"%>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<!-- 検索ボタンをモーダル表示 -->
<div class="modal fade" id="sampleModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        <h4 class="modal-title">検索</h4>
      </div>
      <div class="modal-body">
        <% if user_signed_in? %>
          <%= form_tag(search_path, :method => 'get') do %>
            <%= select_tag(:option, options_for_select([["ユーザー", "1"],["投稿","2"]]))%>
            <%= text_field_tag :search %>
            <%= submit_tag '検索' %>
          <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>
<!-- モーダルここまで -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OctoberApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/429a0092f6.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <div class="header-test">
        <%= render 'layouts/header'%>
      </div>
      <main class="main">
        <%= yield %>
      </main>
  </body>
  <footer>
    <div class="footer-logo">
      <div class="col-xs-3"></div>
      <div class="col-xs-6">
        <div id="footer-area">©乃木坂46応援サイト</div>
      </div>
      <div class="col-xs-3"></div>
    </div>
  </footer>
</html>